### ISSUE TITLE
App log shows LS110Water log not found

### ISSUE THREAD

**Issue by tlangelaar** [gruijter/com.gruijter.enelogic#11]
I'm running the following setup:
- Homey firmware 2.0.4
- Enelogic app version 2.4.0 
- Homey (Android) app version 2.0.8.257

And added two devices:
- LS120 P1
- LS120 Water

The latter has the following settings :
- No password
- polling interval 350 ms
- 1000 pulses per m3
- Automatic calibration true
- Log raw sensor data true (not sure I need this) 

Both devices seem to work properly. 
And have the log of this app show the following lines every two seconds :
2019-02-27 22:14:32 [err] [ManagerDrivers] [LS110Water] [0] { Error: log_not_found at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190) at JSON.parse () at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083) at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379) at Array.map () at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372) at emitTwo (events.js:126:13) at process.emit (events.js:214:7) at emit (internal/child_process.js:762:12) at _combinedTickCallback (internal/process/next_tick.js:142:11) message: ‘log_not_found’, code: 404 }

**Comment by gruijter** [comment]
Thx 4 reporting!

You can disable the log raw sensor data. That is only needed if you want to check if your device is placed correctly on the water meter. Furthermore, I think I might have solved the issue with the log error in v 2.5.0 of the app. Available as beta in the appstore. Pls let et me know if that fixes it or not.

**Comment by tlangelaar** [comment]
Just installed 2.5.0 beta. The log doesn't show the error anymore, tested a couple of minutes. Was it an incorrect error logging or was there indeed something not working properly?

And of course thank you very much for the fix and quick response!

**Comment by gruijter** [comment]
The error was caused by a Homey firmware change in v2.
