### ISSUE TITLE
My youless stopped working after update to v4.4.0

### ISSUE THREAD

**Issue by floreseken** [gruijter/com.gruijter.enelogic#34]
It hung on the last measurement. I removed the devce and re-added it, but that does not help.

Logging:
2023-12-03T19:30:34.026Z [err][Driver:LS120] [Device:7df66e1c-b135-498a-87f7-38c6965b9bdf] Error: Page Not found
    at Youless._makeRequest (/node_modules/youless/youless.js:741:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Youless.getP1Status (/node_modules/youless/youless.js:317:19)
    at async LS120Device.migrate (/drivers/LS120/device.js:119:21)
    at async LS120Device.onInit (/drivers/LS120/device.js:64:24)
    at async LS120Device._onInit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:1682)

2023-12-03T19:30:34.023Z [err][Driver:LS120] [Device:7df66e1c-b135-498a-87f7-38c6965b9bdf] Migration failed Error: Page Not found
    at Youless._makeRequest (/node_modules/youless/youless.js:741:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Youless.getP1Status (/node_modules/youless/youless.js:317:19)
    at async LS120Device.migrate (/drivers/LS120/device.js:119:21)
    at async LS120Device.onInit (/drivers/LS120/device.js:64:24)
    at async LS120Device._onInit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:1682)

2023-12-03T19:30:29.002Z [log][Driver:LS120] [Device:7df66e1c-b135-498a-87f7-38c6965b9bdf] checking migration for LS120P1_192.168.1.111

2023-12-03T19:30:29.001Z [log][Driver:LS120] [Device:7df66e1c-b135-498a-87f7-38c6965b9bdf] device init:  LS120P1_192.168.1.111 id: LS120P1_72:b8:a:14:26:a9

2023-12-03T19:30:20.621Z [err][Driver:LS120] Error: Page Not found
    at Youless._makeRequest (/node_modules/youless/youless.js:741:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Youless.getP1Status (/node_modules/youless/youless.js:317:19)
    at async /drivers/LS120/driver.js:98:22

Could i be that this only works with another firmware on my youless? I'm running 1.4.1-EL right now.

**Comment by floreseken** [comment]
I just updated my youless firmware to v1.6.0 and everything started to work again.

You might want of fix this? Because I might not be the only one that is running an older version..

**Comment by gruijter** [comment]
Thx 4 reporting! Will investigate it.

**Comment by barendbigfoot** [comment]
Same issues here! with firmware 1.4.5-EL

**Comment by barendbigfoot** [comment]
after updating the youless from 1.4.5.-EL to 1.6 EL youless device is dead ....

**Comment by gruijter** [comment]
@barendbigfoot please contact youLess if your LS120 went dead after firmware upgrade.

Others: new version 4.4.2 is ready for testing: https://homey.app/a/com.gruijter.enelogic/test/

This should work with older YouLess firmware.

Can you please install, test, and give feedback?

**Comment by barendbigfoot** [comment]
It works after upgrading to 1.6 EL (and my Youless also, did not like to upgrade behind a wifi ethernet router.).
