### ISSUE TITLE
2.0.3 crashes with a SyntaxError

### ISSUE THREAD

**Issue by carel** [gruijter/com.gruijter.enelogic#4]
Hi!

After an upgrade to 2.0.3

Unfortunately, the app crashed while it tried to show the Enelogic  power usage ledring screensaver.

This is the stack trace:

```
/drivers/enelogicp1/device.js:114
				};
				^
SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
```

**Comment by carel** [comment]
Thanks for fixing the issue in 2.0.4 Robin!
