### ISSUE TITLE
cant connect my ls110 to E or W

### ISSUE THREAD

**Issue by jap2slow** [gruijter/com.gruijter.enelogic#8]
error log
2018-12-27 17:04:18 [err] [ManagerDrivers] [LS110Water] Pair error Error: Info could not be retrieved from device at Youless.getInfo (/node_modules/youless/youless.js:185:11) at at process._tickCallback (internal/process/next_tick.js:189:7) 
2018-12-27 17:04:18 [log] [ManagerDrivers] [LS110Water] save button pressed in frontend 
2018-12-27 17:04:07 [err] [ManagerDrivers] [LS110] Pair error Error: Info could not be retrieved from device at Youless.getInfo (/node_modules/youless/youless.js:185:11) at at process._tickCallback (internal/process/next_tick.js:189:7) 
2018-12-27 17:04:07 [log] [ManagerDrivers] [LS110] save button pressed in frontend

**Comment by gruijter** [comment]
Have you set a password on the device? If so, could you try with the password removed?

**Comment by jap2slow** [comment]
there are no password on my devices, I have one for Electrical and one for Gas

**Comment by gruijter** [comment]
fixed in v 2.2.0
